### ISSUE TITLE
Monotonic Prometheus counter sent to Datadog as gauge

### ISSUE THREAD

**Issue by FRosner** [vectordotdev/vector#10171]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-musl 2021-04-29)
```

### Vector Configuration File

```yaml
sinks:
  sink-datadog-5830cf04-375c-11ec-b42a-2267bbbe956d:
    type: datadog_metrics
    inputs:
      - filter-5830cf04-375c-11ec-b42a-2267bbbe956d
    api_key: <redacted>
    default_namespace: 5830cf04-375c-11ec-b42a-2267bbbe956d
    healthcheck:
      enabled: true
transforms:
  filter-5830cf04-375c-11ec-b42a-2267bbbe956d:
    type: filter
    inputs:
      - prom_source
    condition: |-
      .tags.uuid == "5830cf04-375c-11ec-b42a-2267bbbe956d"
```

```yaml
sources:
  prom_source_raw:
    type: prometheus_remote_write
    address: 0.0.0.0:9000
transforms:
  prom_source:
    type: filter
    inputs:
      - prom_source_raw
    condition: |-
      includes([
        "coordinator_rate_limited_requests_total",
        "coordinator_read_requests_failures_total",
        "coordinator_read_requests_timeouts_total",
        "coordinator_read_requests_unavailables_total",
        "coordinator_write_requests_failures_total",
        "coordinator_write_requests_timeouts_total",
        "coordinator_write_requests_unavailables_total",
        "coordinator_range_requests_failures_total",
        "coordinator_range_requests_timeouts_total",
        "coordinator_range_requests_unavailables_total",
        "coordinator_write_latency_seconds_count",
        "coordinator_write_latency_seconds_bucket",
        "coordinator_write_requests_mutation_size_bytes_bucket",
        "coordinator_read_latency_seconds_count",
        "coordinator_read_latency_seconds_bucket",
        "coordinator_range_latency_seconds_count",
        "coordinator_range_latency_seconds_bucket"
      ], .name)
api:
  enabled: true
```

### Debug Output

```
vector-agent Nov 24 15:30:03.040 DEBUG sink{component_kind="sink" component_name=sink-datadog-5830cf04-375c-11ec-b42a-2267bbbe956d component_type=datadog_metrics}: vector::utilization: utilization=0.00000004091731467404702
vector-agent Nov 24 15:30:03.040 TRACE vector: Beep.
vector-agent Nov 24 15:30:04.040 TRACE vector: Beep.
vector-agent Nov 24 15:30:05.040 TRACE vector: Beep.
vector-agent Nov 24 15:30:06.042 TRACE vector: Beep.
vector-agent Nov 24 15:30:07.041 TRACE vector: Beep.
vector-agent Nov 24 15:30:08.000 DEBUG transform{component_kind="transform" component_name=prom_source component_type=filter}: vector::utilization: utilization=0.000000041515844030928795
vector-agent Nov 24 15:30:08.001 DEBUG transform{component_kind="transform" component_name=filter-5830cf04-375c-11ec-b42a-2267bbbe956d component_type=filter}: vector::utilization: utilization=0.00000004058764228221605
vector-agent Nov 24 15:30:08.039 DEBUG sink{component_kind="sink" component_name=sink-datadog-5830cf04-375c-11ec-b42a-2267bbbe956d component_type=datadog_metrics}: vector::utilization: utilization=0.00000004189794842444171
vector-agent Nov 24 15:30:08.040 TRACE vector: Beep.
vector-agent Nov 24 15:30:09.040 TRACE vector: Beep.
vector-agent Nov 24 15:30:10.041 TRACE vector: Beep.
vector-agent Nov 24 15:30:11.041 TRACE vector: Beep.
vector-agent Nov 24 15:30:12.041 TRACE vector: Beep.
vector-agent Nov 24 15:30:13.000 DEBUG transform{component_kind="transform" component_name=prom_source component_type=filter}: vector::utilization: utilization=0.00000004141203013191902
vector-agent Nov 24 15:30:13.001 DEBUG transform{component_kind="transform" component_name=filter-5830cf04-375c-11ec-b42a-2267bbbe956d component_type=filter}: vector::utilization: utilization=0.000000038979361242264764
vector-agent Nov 24 15:30:13.039 DEBUG sink{component_kind="sink" component_name=sink-datadog-5830cf04-375c-11ec-b42a-2267bbbe956d component_type=datadog_metrics}: vector::utilization: utilization=0.00000004253021128412869
```

### Problem

We have a use case where we are scraping k8s pods using Prometheus, forwarding those scrapes to vector.dev using Prometheus remote write, and then forwarding these metrics to Datadog.

Some of the metrics are counters (e.g. `coordinator_rate_limited_requests_total`) but it appears they are recognized as gauges in Datadog. According to https://docs.datadoghq.com/integrations/guide/prometheus-metrics/ we have to set send_monotonic_counter but I can't find this option in https://vector.dev/docs/reference/configuration/sinks/datadog_metrics/. How can we export Prometheus counters correctly to Datadog using vector.dev?

### Example Data

![image](https://user-images.githubusercontent.com/3427394/143268496-615e1cbb-3e23-43f3-82e7-f2dda3c5751a.png)

### Additional Context

We are running vector in Kubernetes and the remote write is performed by VictoriaMetrics vmagent. It is also written to VictoriaMetrics vminsert however, and the counters show up correctly in Grafana at least.

**Comment by jszwedko** [comment]
Hi @FRosner ! Thanks for creating this. Just to sanity check, could you try with the newest version of Vector: 0.18.0? It's possible this was a bug that was fixed.

**Comment by FRosner** [comment]
I've upgraded and tested with 0.18.0 and it is still happening. Is vector supposed to set `send_monotonic_counter` and if so, based on what logic? A code search didn't return anything unfortunately (https://github.com/vectordotdev/vector/search?q=send_monotonic_counter)

**Comment by jszwedko** [comment]
Hi @FRosner !

So Vector _should_ already be sending counters as counters to Datadog. You can see where this conversion happens to Datadog's API types here:

https://github.com/vectordotdev/vector/blob/17d86cc815785d63c3fcdc160c207b1fc9b03751/src/sinks/datadog/metrics/encoder.rs#L443-L449

I'm wondering if the metric registers as a counter or a gauge in Vector before it is sent to Datadog. Would you be able to grab the metric in question in the Vector instance sending to Datadog? You can use `vector tap` or add a `console` sink with `encoding.codec = "json"` to get the metric as it is represented in Vector. That would help narrow down where the problem is.

**Comment by FRosner** [comment]
I added the json encoded console sink and as expected, it's claiming that it is a gauge.

```
{"name":"coordinator_write_latency_seconds_count","tags":{},"kind":"absolute","gauge":{"value":0.0}}
```

Let me find a way to tap into the remote write protocol / see what is being sent by vmagent.

**Comment by FRosner** [comment]
I've inspected the original scrapes and noticed that the `coordinator_write_latency_seconds_count` comes from a histogram, which exposes `coordinator_write_latency_seconds_bucket`, `coordinator_write_latency_seconds_count`, `coordinator_write_latency_seconds_sum`

```
# HELP coordinator_write_latency_seconds
# TYPE coordinator_write_latency_seconds histogram
```

However, I also checked for something that is a counter

```
# HELP commitlog_runs_total
# TYPE commitlog_runs_total counter
commitlog_runs_total{...} 44212.0
```

And it is exported as a Gauge as well. So I'm not 100% sure if that is the reason. I'll continue after lunch, trying to tap into the remote write protocol somehow.

**Comment by FRosner** [comment]
If I understand the remote write format correctly, it does not seem to transmit anything but the labels and value? https://github.com/VictoriaMetrics/VictoriaMetrics/blob/083044c3e2f61f8f529989d699c25213e22dda2a/lib/prompbmarshal/types.pb.go#L18-L21. I've pinged the VictoriaMetrics folks at Slack and asked if they can confirm.

**Comment by FRosner** [comment]
I've heard back from the VictoriaMetrics folks and they say that "vmagent doesn't collect HELP and TYPE information, because it's not stored at VictoriaMetrics and there is no sense to collect it."

So I guess there isn't anything we can do to fix that other than scraping metrics with vector agents? I'm not sure how well it performs wrt to discovering scraping targets dynamically based on annotations and scalability (we have ten thousands of targets and sometimes scrape sizes up to 64 MB). Do you have any experience with that? I am trying vector for the first time now.

**Comment by FRosner** [comment]
One question, @jszwedko : Would be possible to change it from gauge to counter using VRL?

```
"kind":"absolute","gauge":{"value":58579.0}
```

If I remap that to

```
"kind":"???","???":{"value":58579.0}
```

Would that work? And if yes, what would be the values for `???`?

**Comment by FRosner** [comment]
I've checked the docs and I think it would be

```
{"counter":{"value":1},"kind":"incremental"}
```

**Comment by FRosner** [comment]
I tried it but it doesn't seem to work to remove gauge and add counter. I can change the kind but those fields seem not to be modifiable :/

**Comment by jszwedko** [comment]
Hi @FRosner !

As you discovered, the type of the metric isn't modifiable in `remap` yet. We are thinking about how to enable that though, in a safe way, in https://github.com/vectordotdev/vector/issues/5521

I believe you could use a `lua` transform however. This should allow you to modify _any_ fields. You just have to make sure the structure matches up with how Vector structures metrics, which you've discovered above. In this case, I think it'd look something like:

```
[transforms.map_metric]
type = "lua"
hooks.process = """
function (event, emit)
  event.metric.gauge = event.metric.counter
  event.metric.kind = "incremental"
  emit(event)
"""
```

Let me know if that works for you!

**Comment by FRosner** [comment]
That's great news! I was looking into the lua transform today and was wondering if it might work. So thanks for confirming that :) We'll do the heavy lifting / filtering with remap transforms and filters before and the last step will be the lua transform the change the metric type. I'll try it in the next days and will let you know. Thanks a lot!

I subscribed to #5521 :)

**Comment by jszwedko** [comment]
Just doing some issue clean-up. I'll close this since we are tracking the ability to modify metrics in https://github.com/vectordotdev/vector/issues/5521 . Let me know if you have any other questions though!
