### ISSUE TITLE
prometheus_remote_write error invalid socket address syntax

### ISSUE THREAD

**Issue by Myasnik2000** [vectordotdev/vector#19588]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hey Vector team!
I'm trying to use vector inside my k8s cluster and I have configured Prometheus source like this 
```
sources:
  prometheus:
    type: prometheus_remote_write
    address: http://monitoring-stack-server.prometheus.svc:9090
```
In the address field, I'm using the k8s DNS address of the Prometheus service, but I'm getting this error 
` Configuration error. error=invalid socket address syntax`

### Configuration

```text
sources:
  prometheus:
    type: prometheus_remote_write
    address: http://monitoring-stack-server.prometheus.svc:9090
```
```


### Version

helm chart version: 0.30.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment]
Hi @Myasnik2000 !

The address needs to just be `<host>:<port>`, no `http://`. That should fix the issue for you but feel free to reopen this if it doesn't!

**Comment by Myasnik2000** [comment]
> Hi @Myasnik2000 !
> 
> The address needs to just be `<host>:<port>`, no `http://`. That should fix the issue for you but feel free to reopen this if it doesn't!

Thanks for the quick response @jszwedko.
I've tried the suggested version, but I'm still getting the same error 
` ERROR vector::cli: Configuration error. error=invalid socket address syntax`

**Comment by jszwedko** [comment]
Can you provide the new configuration you are trying/

**Comment by Myasnik2000** [comment]
Sure here is the configuration part:
`  prometheus_remote:
    type: prometheus_remote_write
    address: monitoring-stack-server.prometheus.svc:9090`

**Comment by jszwedko** [comment]
@Myasnik2000 Apologies, I missed that you are trying to configure the `prometheus_remote_write` source rather than sink. For the source, the address should be an address that Vector can bind to to receive data (e.g. `127.0.0.1:9090`). It looks like you want to _consume_ data from some Prometheus server in which case you should set up Vector to receive the data and then configure the Prometheus server to _push_ the data to Vector.

**Comment by Myasnik2000** [comment]
@jszwedko , you mean that I must configure remote_write inside the Prometheus configuration, and send the data to vector, am I right?

**Comment by jszwedko** [comment]
> @jszwedko , you mean that I must configure remote_write inside the Prometheus configuration, and send the data to vector, am I right?

Yep!

**Comment by Myasnik2000** [comment]
okay got it, thanks so much !!!
