### ISSUE TITLE
Ignore Vector VRL failure logs options

### ISSUE THREAD

**Issue by bck01215** [vectordotdev/vector#19597]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I am attempting to retrieve logs from a kafka topic. 50% of the logs are http requests and the rest responses.

In my VRL I only collect the responses with the regex. When a request log is ingested, I get this log

> 2024-01-11T19:47:57.394062Z ERROR transform{component_kind="transform" component_id=f5_decode component_type=remap}: vector_common::internal_event::component_events_dropped: Events dropped intentional=false count=1 reason="Mapping failed with event." internal_log_rate_limit=true

I want to silently fail on unmatching regex

### Attempted Solutions

set `drop_on_error: true` setting and still received error logs in app.

### Proposal

New field to silence errors

### Version

vector 0.34.2 (aarch64-unknown-linux-gnu d685a16 2024-01-02 14:59:54.890517436)

**Comment by jszwedko** [comment]
I believe this is actually fixed in v0.35.0. Do you mind trying that version?

**Comment by bck01215** [comment]
> I believe this is actually fixed in v0.35.0. Do you mind trying that version?

I still receive the same logs in  0.35.0

`docker run --name=vector1 --network="prometheus" -i -v $(pwd)/:/etc/vector/  --rm timberio/vector:0.35.0-debian`

**Comment by jszwedko** [comment]
Can you provide your configuration?

**Comment by jszwedko** [comment]
Ah, sorry, I missed you said `drop_on_error: true`. In that case the logs are expected.

**Comment by jszwedko** [comment]
To silently fail you can use the VRL code you arrived at to abort instead of bubble up an error. That is the intended way to handle this case so I'll close this out, but thank you for raising it!
