### ISSUE TITLE
On kafka consumer rebalance, Vector consumer stops consuming.

### ISSUE THREAD

**Issue by ADustyOldMuffin** [vectordotdev/vector#22006]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We have observed that when a connectivity problem causes consumer groups to change Vector will randomly stop consuming from the associated topic and consumer lag will build up in Kafka.

rdkafka has various issues introduced in version 0.34.0 -> 0.36.0 
- https://github.com/fede1024/rust-rdkafka/issues/638
  - https://github.com/fede1024/rust-rdkafka/issues/638#issue-2037837699
  - https://github.com/fede1024/rust-rdkafka/issues/638#issuecomment-2269415954
  - https://github.com/fede1024/rust-rdkafka/issues/638#issuecomment-1852663124
  - https://github.com/fede1024/rust-rdkafka/issues/638#issuecomment-185339987
  - https://github.com/fede1024/rust-rdkafka/issues/638#issuecomment-1890756211

Vector specifically uses the `StreamConsumer` to consume from Kafka via the source component which is indicated as having an issue. 

Inside of these issues the report that v0.35.0 should be okay, but from this PR https://github.com/fede1024/rust-rdkafka/pull/666 which fixes the issue it would still be present v0.35.0 for the `StreamConsumer` as seen [here](https://github.com/fede1024/rust-rdkafka/pull/666/files#diff-9285f3156addeff1289e607bb323f8534557b1f4389ff21575d34bef39b7508aL137-R170).

### Version

0.40.0

### Additional Context

We'd like to propose to upgrade rdkafka to version [0.37.0](https://github.com/fede1024/rust-rdkafka/releases/tag/v0.37.0) to fix the issue as we've identified that the fix for `StreamConsumer` is in this release.

Until then, we have to monitor kafka and restart Vector when this happens. It also of note that due to https://github.com/vectordotdev/vector/issues/21134 we can't just monitor Vector as the metrics that indicate something is wrong are currently incorrect.

**Comment by ADustyOldMuffin** [comment]
You can see the PR chore bumping it here https://github.com/vectordotdev/vector/pull/21929 just to document that this will resolve a fairly large issue.

**Comment by sam6258** [comment]
So I think #21134 is actually caused by the `StreamConsumer` race. I took a look at where the metrics are in Vector and its just a callback into the rust library. It would make sense if the consumer thread goes idle for a particular partition that it doesn't update its lag metric.

**Comment by fpytloun** [comment]
rdkafka update should be in v0.44.0. Did anyone test if this issue is fixed?

**Comment by ADustyOldMuffin** [comment]
We tested and it did not indeed fix our issue. We did however lower the number of consumers and it seems to have fixed it. We found some upstream issues stating that the old protocol has issues with a large number of consumers, and is fixed in the new consumer protocol in Kafka (which isn't GA yet I think).

**Comment by yalinglee** [comment]
Not sure if it's the same issue, but on a few occasions we've seen Vector (0.47.0) stop consuming logs after outputting this message: 
```
{"log.file":"/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rdkafka-0.37.0/src/client.rs","log.line":80,"log.module_path":"rdkafka::client","log.target":"librdkafka","message":"librdkafka: PARTCNT [thrd:main]: Topic xxx partition count changed from 24 to 26"
```
When this happened, the memory usage for the affected k8s pods would keep growing until they were restarted.

**Comment by slice-tarun** [comment]
I think the issue persists still in vector (0.49.0) which stops consuming logs. Needa restart of vector pods everytime

**Comment by tanganellilore** [comment]
Hi team,
I think is present also on 0.54 and 0.55 release.
I think that during shorts rebalance some partition casually stop to consumer and only restart of instance restart the ingestion.

No error was printed on stdout.
